
[<< 메인으로](https://github.com/AtomicLiquors/Java_Wiki_Chb)

&nbsp;  

# 자동자원반환 : try-with-resources
JDK 1.7부터 추가되었다.  
주로 입출력(I/O)와 관련된 클래스를 사용할 때 유용한데,  
사용한 다음 반드시 닫아줘서 자원을 반환해야 하는 클래스가 많기 때문이다.

&nbsp;  
### Before
```java
try{
    fis = new FileInputStream("score.dat");
    dis = new DataInputStream(fis);
} catch (IOException ie){
    ie.printStackTrace();
} finally {
    dis.close();
    //작업 중 예외가 발생했더라도, dis가 닫히도록 finally 블럭에 넣는다.
}
```
얼핏 잘 설계된 코드 같지만,  
위 코드의 문제는 close() 또한 예외를 발생시킬 가능성이 있다는 것이다.


&nbsp;  
```java
try{
    fis = new FileInputStream("score.dat");
    dis = new DataInputStream(fis);
} catch (IOException ie){
    ie.printStackTrace();
} finally {
    try{
        if(dis!=null)
            dis.close();
    }catch(IOException ie){
        ie.printStackTrace();
    }
}
```
이렇게 수정하면 코드가 복잡해 보이는 문제도 있지만,  
try블럭과 finally블럭에서 모두 예외가 발생하면,   
**try블럭의 예외는 무시된다는 결점이 있다.**

&nbsp;  
&nbsp;  
### After
```java
try(fis = new FileInputStream("score.dat");
    dis = new DataInputStream(fis)){
    while(true){
        score = dis.readInt();
        System.out.println(score);
        sum += score;
    }
}catch (EOFException e){
    System.out.println("정수의 총합은 " + sum + "입니다.");
}catch (IOException oe){
    ie.printStackTrace();
}
```
try-with-resources문의 괄호()안에 객체를 생성하는 문장을 넣었다.  
이 객체는 따로 close()를 호출하지 않아도,  
try를 벗어나는 순간 자동으로 close()가 호출된다.

이 때, 대상 클래스는 AutoCloseable이라는 인터페이스를 구현implement한 것이어야 한다.

&nbsp;  
### 자동 호출된 close()에서 예외가 발생하면 어떻게 될까?
자바의 정석 437페이지.
